// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

console.log("Hello, BuckleScript and Reason, this is my tutorial!");

function speak(animal) {
  if (animal.tag) {
    return animal[0] + " says: woof";
  } else {
    return animal[0] + " says: meow";
  }
}

console.log(speak(/* Cat */Block.__(0, ["Rooni"])));

exports.speak = speak;
/*  Not a pure module */
